name: Deploy Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: |
          if [ -f /home/ubuntu/dev/env/.env ]; then
            set -o allexport
            source /home/ubuntu/dev/env/.env
            set +o allexport
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -reconfigure -input=false

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
