name: Deploy Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: |
          if [ -f /home/ubuntu/dev/env/.env ]; then
            set -o allexport
            source /home/ubuntu/dev/env/.env
            set +o allexport
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -backend-config="bucket=$STATE_BUCKET_NAME" -backend-config="key=$STATE_KEY" -backend-config="region=$STATE_BUCKET_REGION" -backend-config="dynamodb_table=$LOCK_TABLE_NAME"

      - name: Terraform Plan
        run: terraform plan -var="ecr_repository_url=$ECR_REPOSITORY_URL" -var="subnet_ids=$SUBNET_IDS" -var="security_group_ids=$SECURITY_GROUP_IDS" -var="aws_region=$AWS_DEFAULT_REGION"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ecr_repository_url=$ECR_REPOSITORY_URL" -var="subnet_ids=$SUBNET_IDS" -var="security_group_ids=$SECURITY_GROUP_IDS" -var="aws_region=$AWS_DEFAULT_REGION"
